project:
  type: website
  output-dir: docs

website:
  title: "RPAD 88X - Doctoral Professional Development Seminar"
  navbar:
    background: primary
    left:
      - text: "About"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus88x.qmd
      - text: "Resources"
        file: resources.qmd
        
  sidebar: 
    - title: "Home"
      style: "docked"
      search: true
      contents: 
        - href: index.qmd
        
    - title: "Resources"
      contents: 
        - href: resources.qmd
        - href: data.qmd
        - href: templates.qmd
        
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

