project:
  type: website
  output-dir: docs

website:
  title: "RPAD 88X - Doctoral Professional Development Seminar"
  navbar:
    background: primary
    left:
      - text: "About"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus88x.qmd
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

